# Generated by Django 2.2.1 on 2019-05-25 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='task name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Projects')),
            ],
        ),
    ]
